
clone_depth: 5

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"
  - LUA: "luajit 2.0"
  - LUA: "luajit 2.1"

before_build:
  - set PATH=%CD%\env\bin;C:\Python27\Scripts;%PATH% # Add directory containing 'pip'
  - pip install hererocks                            # to PATH, too.
  - hererocks env --%LUA% -rlatest
  - luarocks install busted

build_script:
  - luarocks make

test_script:
  - busted
